endpoints:
  prometheus:
    sensitive: false

micronaut:
  application:
    name: mqgateway
  metrics:
    enabled: true
  server:
    cors:
      enabled: true

gateway:
  app-version: <%=version%>
  config-path: gateway.yaml
  system:
    network-adapter: eth0
    platform: NANOPI
    expander:
      enabled: false
    components:
      serial:
        enabled: true
        device: "/dev/ttyS1"
        baud: 9600

homeassistant:
  enabled: true
  root-topic: "homeassistant"